services:
  api:
    build: .
    ports:
      - 8000:8000
    image: minecraft-api
    volumes:
      - ~/.aws:/root/.aws
      - .:/app
    environment:
      AWS_PROFILE: mlops-club
      DEV_PORT: 8000
      DEPLOY_SERVER_STATE_MACHINE_ARN: arn:aws:states:us-west-2:630013828440:stateMachine:awscdkminecraftProvisionMcStateMachine10154FE5-7A5lw7MAZmIw
      DESTROY_SERVER_STATE_MACHINE_ARN: arn:aws:states:us-west-2:630013828440:stateMachine:awscdkminecraftDeprovisionMcStateMachineCA7C20D8-6hAlKIqfh4hR
      ENVIRONMENT: development
      CLOUD_FORMATION_STACK_NAME: awscdk-minecraft-server
      CLOUD_FORMATION_SERVER_IP_OUTPUT_KEY_NAME: MinecraftServerIp

# Get a valid requet to got from our frontend to back end
