services:

  api:
    build: .
    ports:
      - 8000:8000
    image: rest-api
    volumes:
      - ~/.aws:/root/.aws
      - .:/app
    environment:
      AWS_PROFILE: mlops-club
      DEV_PORT: 8000
      ENVIRONMENT: development

# Get a valid requet to got from our frontend to back end
