services:

  api:
    build: .
    ports:
      - 8000:8000
    image: mlops-club/serverless-fastapi
    volumes:
      - ~/.aws:/root/.aws
      - .:/app
    environment:
      AWS_PROFILE: mlops-club
      DEV_PORT: 8000
      ENVIRONMENT: development
      S3_BUCKET_NAME: awscdk-minecraft-bucket43879c71-5acoum234t7e
